language: ruby
rvm:
  - 2.0.0
before_script:
  - cp config/config.yml.sample config/config.yml
  - cp config/database.yml.sample config/database.yml
  - bundle exec rake db:test:prepare
script:
  - bundle exec rake spec
  - bundle exec rake cucumber
